chaine = input("entrer une chaine de caractere:")
sous_chaine = input("entrer la sous_chaine:")
position = chaine.find(sous_chaine)
print("la position de la sous chaine est :", position)
#eror f index o find tatl3 -1 ( susbstring not find)
